# Generated by Django 2.0.7 on 2018-10-24 21:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initsys', '0005_auto_20181024_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('idordendecompra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeEntrada',
            fields=[
                ('idordendeentrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('idpieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=6, default=0.0, max_digits=13)),
                ('porcentaje_de_iva', models.DecimalField(decimal_places=2, default=16.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
        ),
        migrations.CreateModel(
            name='Piezas_OrdenDeCompra',
            fields=[
                ('idpiezas_ordendecompra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('ordendecompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.OrdenDeCompra')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Pieza')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
        ),
        migrations.CreateModel(
            name='Piezas_OrdenDeEntrada',
            fields=[
                ('idpiezas_ordendeentrada', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=6, default=0.0, max_digits=13)),
                ('importe', models.DecimalField(decimal_places=6, default=0.0, max_digits=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('ordendeentrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.OrdenDeEntrada')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Pieza')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=254, null=True)),
                ('rfc', models.CharField(max_length=13)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('extension', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedor', to='initsys.Direccion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor_Piezas',
            fields=[
                ('idproveedor_piezas', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Pieza')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
        ),
        migrations.AddField(
            model_name='pieza',
            name='proveedores',
            field=models.ManyToManyField(through='inventario.Proveedor_Piezas', to='inventario.Proveedor'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='ordendeentrada',
            name='piezas',
            field=models.ManyToManyField(through='inventario.Piezas_OrdenDeEntrada', to='inventario.Pieza'),
        ),
        migrations.AddField(
            model_name='ordendeentrada',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenesdeentrada', to='inventario.Proveedor'),
        ),
        migrations.AddField(
            model_name='ordendeentrada',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='piezas',
            field=models.ManyToManyField(through='inventario.Piezas_OrdenDeCompra', to='inventario.Pieza'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenesdecompra', to='inventario.Proveedor'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
    ]
