# Generated by Django 2.0.7 on 2018-11-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0004_auto_20181029_1104'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='claveprodserv',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'ClaveProdServ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_claveprodserv', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='claveunidad',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'ClaveUnidad'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_claveunidad', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='impuesto',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'Impuesto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_impuesto', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='tipofactor',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'TipoFactor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_tipofactor', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='piezas',
            field=models.ManyToManyField(related_name='ordenes_de_compra', through='inventario.Piezas_OrdenDeCompra', to='inventario.Pieza'),
        ),
        migrations.AlterField(
            model_name='ordendeentrada',
            name='piezas',
            field=models.ManyToManyField(related_name='ordenes_de_entrada', through='inventario.Piezas_OrdenDeEntrada', to='inventario.Pieza'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='proveedores',
            field=models.ManyToManyField(related_name='piezas', through='inventario.Proveedor_Piezas', to='inventario.Proveedor'),
        ),
    ]
