# Generated by Django 2.0.7 on 2018-11-28 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20181127_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordendecompra',
            options={'ordering': ['-fecha', 'proveedor']},
        ),
        migrations.AlterModelOptions(
            name='ordendeentrada',
            options={'ordering': ['-fecha', 'proveedor']},
        ),
        migrations.AlterModelOptions(
            name='pieza',
            options={'ordering': ['nombre', 'marca', 'modelo']},
        ),
        migrations.AlterModelOptions(
            name='piezas_ordendecompra',
            options={'ordering': ['ordendecompra', 'pieza']},
        ),
        migrations.AlterModelOptions(
            name='piezas_ordendeentrada',
            options={'ordering': ['ordendeentrada', 'pieza']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre', 'razon_social']},
        ),
        migrations.AlterModelOptions(
            name='proveedor_piezas',
            options={'ordering': ['proveedor', 'pieza']},
        ),
        migrations.AddField(
            model_name='ordendeentrada',
            name='orden_de_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_de_entrada', to='inventario.OrdenDeCompra'),
        ),
    ]
