# Generated by Django 2.0.7 on 2018-11-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20181127_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='maximo_inventario',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pieza',
            name='minimo_inventario',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
