# Generated by Django 2.0.7 on 2018-11-30 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20181129_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ordendeentrada',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
