# Generated by Django 2.0.7 on 2018-11-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20181129_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piezas_ordendecompra',
            name='ordendecompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas_requeridas', to='inventario.OrdenDeCompra'),
        ),
        migrations.AlterField(
            model_name='piezas_ordendecompra',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenesdecompra_en_que_se_requiere', to='inventario.Pieza'),
        ),
    ]
