# Generated by Django 2.0.7 on 2018-12-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20181204_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piezas_ordendeentrada',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_de_entrada_en_que_llega', to='inventario.Pieza'),
        ),
    ]
