# Generated by Django 2.0.7 on 2018-12-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20181205_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='sku',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor_piezas',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='proveedor_piezas',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp_provedores', to='inventario.Pieza'),
        ),
        migrations.AlterField(
            model_name='proveedor_piezas',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp_piezas', to='inventario.Proveedor'),
        ),
    ]
