# Generated by Django 2.0.7 on 2018-12-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20181211_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
