# Generated by Django 2.0.7 on 2019-01-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20190116_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='piezas_ordendeentrada',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='piezas_ordendeentrada',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='proveedor_piezas',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
