# Generated by Django 2.0.7 on 2019-01-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20190122_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendeentrada',
            name='orden_de_compra',
            field=models.ForeignKey(blank=True, limit_choices_to={'orden_de_entrada__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_de_entrada', to='inventario.OrdenDeCompra'),
        ),
    ]
