"""
Django settings for bmhaus project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import mimetypes

from .main_settings import *

mimetypes.add_type('text/css', '.css', True)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = MAIN_SECRET_KEY()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DEBUG_MODE()

ALLOWED_HOSTS = MAIN_ALLOWED_HOSTS()


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'crispy_forms',
    'django.contrib.humanize',

    'initsys',
    'cfdi',
    'flujo',
    'inventario',
    'app',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bmhaus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "html_templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'bmhaus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = MAIN_DATABASES(os, BASE_DIR)


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True

EMAIL_HOST = 'mail.bmhaus.mx'
EMAIL_PORT = '465'
EMAIL_HOST_USER = 'no-reply@bmhaus.mx'
EMAIL_HOST_PASSWORD = 'esteauto2018$'
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'Soporte BM haus <no-reply@bmhaus.mx>'

FILE_UPLOAD_MAX_MEMORY_SIZE = 8400000
DATA_UPLOAD_MAX_MEMORY_SIZE = 5250000

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
SESSION_SAVE_EVERY_REQUEST = True

if DEBUG is False:
    STATIC_ROOT = os.path.join('/home/bmhausm/public_html/', 'static/')
    MEDIA_ROOT = os.path.join('/home/bmhausm/public_html/', 'media/')
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'files/static/')
    MEDIA_ROOT = os.path.join(BASE_DIR, 'files/media/')
