# Generated by Django 2.0.7 on 2018-10-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181029_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='linea',
            new_name='serie',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_de_motor',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_de_serie',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
