# Generated by Django 2.0.7 on 2018-10-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181025_1243'),
        ('app', '0006_auto_20181029_1250'),
    ]

    operations = [
    ]
