# Generated by Django 2.0.7 on 2018-10-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181029_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['first_name', 'last_name', 'apellido_materno']},
        ),
        migrations.AlterModelOptions(
            name='doctoordenreparacion',
            options={'ordering': ['fecha_y_hora_de_recepcion']},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['numero_de_placa', 'marca', 'serie', 'modelo']},
        ),
    ]
