# Generated by Django 2.0.7 on 2018-10-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20181029_1744'),
        ('app', '0007_auto_20181029_2307'),
    ]

    operations = [
    ]
