# Generated by Django 2.0.7 on 2018-10-30 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20181030_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoordenreparacion',
            name='fecha_y_hora_de_recepcion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
