# Generated by Django 2.0.7 on 2018-11-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181103_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoordenreparacion',
            old_name='GeneratorExitmaneral_de_gato',
            new_name='bocinas',
        ),
        migrations.RenameField(
            model_name='doctoordenreparacion',
            old_name='bocinas_de_claxonencendedor',
            new_name='claxon',
        ),
        migrations.AddField(
            model_name='doctoordenreparacion',
            name='encendedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoordenreparacion',
            name='gato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoordenreparacion',
            name='maneral_de_gato',
            field=models.BooleanField(default=False),
        ),
    ]
