# Generated by Django 2.0.7 on 2018-11-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20181104_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['marca', 'serie', 'tipo', 'numero_de_placa']},
        ),
    ]
