# Generated by Django 2.0.7 on 2019-01-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190116_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='avanceenflujo',
            name='fotografia_2',
            field=models.ImageField(blank=True, upload_to='avanceenflujo'),
        ),
        migrations.AddField(
            model_name='avanceenflujo',
            name='fotografia_3',
            field=models.ImageField(blank=True, upload_to='avanceenflujo'),
        ),
        migrations.AddField(
            model_name='avanceenflujo',
            name='fotografia_4',
            field=models.ImageField(blank=True, upload_to='avanceenflujo'),
        ),
        migrations.AddField(
            model_name='avanceenflujo',
            name='fotografia_5',
            field=models.ImageField(blank=True, upload_to='avanceenflujo'),
        ),
        migrations.AlterField(
            model_name='avanceenflujo',
            name='fotografia',
            field=models.ImageField(blank=True, default='', upload_to='avanceenflujo'),
            preserve_default=False,
        ),
    ]
