# Generated by Django 2.0.7 on 2019-01-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190116_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoordenreparacion',
            name='costo_de_revision',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=13),
        ),
    ]
