# Generated by Django 2.0.7 on 2018-10-23 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0003_auto_20181022_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('idsetting', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_para_mostrar', models.CharField(max_length=100)),
                ('valor', models.TextField()),
                ('tipo', models.CharField(choices=[('INTEGER', 'Entero'), ('STRING', 'Cadena'), ('TEXT', 'Texto Largo'), ('PICTURE', 'Imagen')], default='STRING', max_length=20)),
                ('es_multiple', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['seccion', 'nombre_para_mostrar'],
            },
        ),
    ]
