# Generated by Django 2.0.7 on 2018-10-24 21:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initsys', '0005_auto_20181024_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addenda',
            fields=[
                ('idaddenda', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['idaddenda'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoSAT',
            fields=[
                ('idcatalogo', models.AutoField(primary_key=True, serialize=False)),
                ('idsat', models.CharField(max_length=250)),
                ('nombre', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CfdiRelacionado',
            fields=[
                ('idcfdirelacionado', models.AutoField(primary_key=True, serialize=False)),
                ('UUID', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['UUID'],
            },
        ),
        migrations.CreateModel(
            name='CfdiRelacionados',
            fields=[
                ('idcfdirelacionados', models.AutoField(primary_key=True, serialize=False)),
                ('TipoRelacion', models.CharField(max_length=25)),
                ('TipoRelacion_txt', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['TipoRelacion'],
            },
        ),
        migrations.CreateModel(
            name='CImpuestos',
            fields=[
                ('idcimpuestos', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['idcimpuestos'],
            },
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('idcomplemento', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['idcomplemento'],
            },
        ),
        migrations.CreateModel(
            name='ComplementoConcepto',
            fields=[
                ('idcomplementoconcepto', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['idcomplementoconcepto'],
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('idcomprobante', models.AutoField(primary_key=True, serialize=False)),
                ('Version', models.CharField(default='3.3', max_length=5)),
                ('Serie', models.CharField(blank=True, max_length=25, null=True)),
                ('Folio', models.CharField(blank=True, max_length=40, null=True)),
                ('Fecha', models.DateTimeField(default=datetime.datetime(2018, 10, 24, 16, 24, 41, 555512))),
                ('Sello', models.TextField(blank=True, null=True)),
                ('FormaPago', models.CharField(blank=True, max_length=25, null=True)),
                ('FormaPago_txt', models.CharField(blank=True, max_length=250, null=True)),
                ('NoCertificado', models.CharField(blank=True, max_length=20, null=True)),
                ('Certificado', models.TextField(blank=True, null=True)),
                ('CondicionesDePago', models.CharField(blank=True, max_length=1000, null=True)),
                ('SubTotal', models.DecimalField(decimal_places=6, max_digits=13)),
                ('Descuento', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('Moneda', models.CharField(blank=True, max_length=25, null=True)),
                ('Moneda_txt', models.CharField(blank=True, max_length=250, null=True)),
                ('TipoCambio', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('Total', models.DecimalField(decimal_places=6, max_digits=13)),
                ('TipoDeComprobante', models.CharField(max_length=25)),
                ('TipoDeComprobante_txt', models.CharField(max_length=250)),
                ('MetodoPago', models.CharField(blank=True, max_length=25, null=True)),
                ('MetodoPago_txt', models.CharField(blank=True, max_length=250, null=True)),
                ('LugarExpedicion', models.CharField(max_length=5)),
                ('Confirmacion', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['Serie', 'Folio', '-Fecha', '-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('idconcepto', models.AutoField(primary_key=True, serialize=False)),
                ('ClaveProdServ', models.CharField(max_length=25)),
                ('ClaveProdServ_txt', models.CharField(max_length=250)),
                ('NoIdentificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('Cantidad', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ClaveUnidad', models.CharField(max_length=25)),
                ('ClaveUnidad_txt', models.CharField(max_length=250)),
                ('Unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('ValorUnitario', models.DecimalField(decimal_places=6, max_digits=13)),
                ('Importe', models.DecimalField(decimal_places=6, max_digits=13)),
                ('Descuento', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ClaveProdServ_txt', 'NoIdentificacion', 'Descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Conceptos',
            fields=[
                ('idconceptos', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_conceptos', to='cfdi.Comprobante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['idconceptos'],
            },
        ),
        migrations.CreateModel(
            name='CRetencion',
            fields=[
                ('idcretencion', models.AutoField(primary_key=True, serialize=False)),
                ('Base', models.DecimalField(decimal_places=6, max_digits=13)),
                ('Impuesto', models.CharField(max_length=25)),
                ('Impuesto_txt', models.CharField(max_length=250)),
                ('TipoFactor', models.CharField(max_length=25)),
                ('TipoFactor_txt', models.CharField(max_length=250)),
                ('TasaOCuota', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Importe', models.DecimalField(decimal_places=6, max_digits=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['Impuesto_txt', 'TipoFactor_txt'],
            },
        ),
        migrations.CreateModel(
            name='CRetenciones',
            fields=[
                ('idcretenciones', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cimpuestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_cretenciones', to='cfdi.CImpuestos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['idcretenciones'],
            },
        ),
        migrations.CreateModel(
            name='CTraslado',
            fields=[
                ('idctraslado', models.AutoField(primary_key=True, serialize=False)),
                ('Base', models.DecimalField(decimal_places=6, max_digits=13)),
                ('Impuesto', models.CharField(max_length=25)),
                ('Impuesto_txt', models.CharField(max_length=250)),
                ('TipoFactor', models.CharField(max_length=25)),
                ('TipoFactor_txt', models.CharField(max_length=250)),
                ('TasaOCuota', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['Impuesto_txt', 'TipoFactor_txt'],
            },
        ),
        migrations.CreateModel(
            name='CTraslados',
            fields=[
                ('idctraslados', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cimpuestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_ctraslados', to='cfdi.CImpuestos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['idctraslados'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPredial',
            fields=[
                ('idcuentapredial', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentasprediales', to='cfdi.Concepto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['Numero'],
            },
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('idemisor', models.AutoField(primary_key=True, serialize=False)),
                ('Rfc', models.CharField(max_length=13)),
                ('Nombre', models.CharField(blank=True, max_length=254, null=True)),
                ('RegimenFiscal', models.CharField(max_length=25)),
                ('RegimenFiscal_txt', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['Nombre', 'Rfc'],
            },
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('idimpuestos', models.AutoField(primary_key=True, serialize=False)),
                ('TotalImpuestosRetenidos', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('TotalImpuestosTrasladados', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodo_impuestos', to='cfdi.Comprobante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['idimpuestos'],
            },
        ),
        migrations.CreateModel(
            name='InformacionAduanera',
            fields=[
                ('idinformacionaduanera', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroPedimento', models.CharField(max_length=21)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinformacionesaduaneras', to='cfdi.Concepto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['NumeroPedimento'],
            },
        ),
        migrations.CreateModel(
            name='OpcionCatalogoSAT',
            fields=[
                ('idopcion', models.AutoField(primary_key=True, serialize=False)),
                ('clave_sat', models.CharField(max_length=25)),
                ('descipcion', models.CharField(max_length=250)),
                ('mostrar_como', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cfdi.CatalogoSAT')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['catalogo', 'mostrar_como'],
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('idparte', models.AutoField(primary_key=True, serialize=False)),
                ('ClaveProdServ', models.CharField(max_length=25)),
                ('ClaveProdServ_txt', models.CharField(max_length=250)),
                ('NoIdentificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('Cantidad', models.DecimalField(decimal_places=6, max_digits=12)),
                ('Unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('ValorUnitario', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('Importe', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ClaveProdServ_opcion', models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'ClaveProdServ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parte_claveprodserv', to='cfdi.OpcionCatalogoSAT')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='cfdi.Concepto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['ClaveProdServ_txt', 'NoIdentificacion', 'Descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('idreceptor', models.AutoField(primary_key=True, serialize=False)),
                ('Rfc', models.CharField(max_length=13)),
                ('Nombre', models.CharField(blank=True, max_length=254, null=True)),
                ('ResidenciaFiscal', models.CharField(blank=True, max_length=25, null=True)),
                ('ResidenciaFiscal_txt', models.CharField(blank=True, max_length=250, null=True)),
                ('NumRegIdTrib', models.CharField(blank=True, max_length=40, null=True)),
                ('UsoCFDI', models.CharField(max_length=25)),
                ('UsoCFDI_txt', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ResidenciaFiscal_opcion', models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'ResidenciaFiscal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptor_residenciafiscal', to='cfdi.OpcionCatalogoSAT')),
                ('UsoCFDI_opcion', models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'UsoCFDI'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptor_usocfdi', to='cfdi.OpcionCatalogoSAT')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='cfdi.Comprobante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['Nombre', 'Rfc'],
            },
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('idretencion', models.AutoField(primary_key=True, serialize=False)),
                ('Impuesto', models.CharField(max_length=25)),
                ('Impuesto_txt', models.CharField(max_length=250)),
                ('Importe', models.DecimalField(decimal_places=6, max_digits=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Impuesto_opcion', models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'Impuesto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retencion_impuesto', to='cfdi.OpcionCatalogoSAT')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['Impuesto_txt'],
            },
        ),
        migrations.CreateModel(
            name='Retenciones',
            fields=[
                ('idretenciones', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('impuestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_retenciones', to='cfdi.Impuestos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['idretenciones'],
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('idtraslado', models.AutoField(primary_key=True, serialize=False)),
                ('Impuesto', models.CharField(max_length=25)),
                ('Impuesto_txt', models.CharField(max_length=250)),
                ('TipoFactor', models.CharField(max_length=25)),
                ('TipoFactor_txt', models.CharField(max_length=250)),
                ('TasaOCuota', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Importe', models.DecimalField(decimal_places=6, max_digits=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Impuesto_opcion', models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'Impuesto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslado_impuesto', to='cfdi.OpcionCatalogoSAT')),
                ('TipoFactor_opcion', models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'TipoFactor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslado_tipofactor', to='cfdi.OpcionCatalogoSAT')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['Impuesto_txt', 'TipoFactor_txt'],
            },
        ),
        migrations.CreateModel(
            name='Traslados',
            fields=[
                ('idtraslados', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('impuestos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_traslados', to='cfdi.Impuestos')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['idtraslados'],
            },
        ),
        migrations.AddField(
            model_name='traslado',
            name='traslados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trasladados', to='cfdi.Traslados'),
        ),
        migrations.AddField(
            model_name='traslado',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='retenciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='cfdi.Retenciones'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='informacionaduanera',
            name='parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinformacionesaduaneras', to='cfdi.Parte'),
        ),
        migrations.AddField(
            model_name='informacionaduanera',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='RegimenFiscal_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'RegimenFiscal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emisor_regimenfiscal', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to='cfdi.Comprobante'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='emisor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='ctraslado',
            name='Impuesto_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'Impuesto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctraslado_impuesto', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='ctraslado',
            name='TipoFactor_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'TipoFactor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctraslado_tipofactor', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='ctraslado',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='ctraslado',
            name='ctraslados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctraslados', to='cfdi.CTraslados'),
        ),
        migrations.AddField(
            model_name='ctraslado',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='cretencion',
            name='Impuesto_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'Impuesto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cretencion_impuesto', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='cretencion',
            name='TipoFactor_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'TipoFactor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cretencion_tipofactor', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='cretencion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='cretencion',
            name='cretenciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cretenciones', to='cfdi.CRetenciones'),
        ),
        migrations.AddField(
            model_name='cretencion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='ClaveProdServ_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'ClaveProdServ'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepto_claveprodserv', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='ClaveUnidad_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'ClaveUnidad'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepto_claveunidad', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='conceptos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='cfdi.Conceptos'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='concepto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='FormaPago_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'FormaPago'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_formapago', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='MetodoPago_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'MetodoPago'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_metodopago', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='Moneda_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'Moneda'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_moneda', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='TipoDeComprobante_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'TipoDeComprobante'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_tipodecomprobante', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='complementoconcepto',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementos', to='cfdi.Concepto'),
        ),
        migrations.AddField(
            model_name='complementoconcepto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='complementoconcepto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='complemento',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementos', to='cfdi.Comprobante'),
        ),
        migrations.AddField(
            model_name='complemento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='complemento',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='cimpuestos',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodo_cimpuestos', to='cfdi.Concepto'),
        ),
        migrations.AddField(
            model_name='cimpuestos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='cimpuestos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='cfdirelacionados',
            name='TipoRelacion_opcion',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__idsat': 'TipoRelacion'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdisrelacionados_tiporelacion', to='cfdi.OpcionCatalogoSAT'),
        ),
        migrations.AddField(
            model_name='cfdirelacionados',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_cfdisrelacionados', to='cfdi.Comprobante'),
        ),
        migrations.AddField(
            model_name='cfdirelacionados',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='cfdirelacionados',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='cfdirelacionado',
            name='cfdirelacionados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfdisrelacionados', to='cfdi.CfdiRelacionados'),
        ),
        migrations.AddField(
            model_name='cfdirelacionado',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='cfdirelacionado',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='addenda',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addendas', to='cfdi.Comprobante'),
        ),
        migrations.AddField(
            model_name='addenda',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='addenda',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
    ]
