# Generated by Django 2.0.7 on 2018-10-29 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0003_auto_20181029_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
