# Generated by Django 2.0.7 on 2018-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciaflujo',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instanciahistoria',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instanciahistoriadetalle',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
    ]
