# Generated by Django 2.0.7 on 2018-11-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_auto_20181103_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='estado',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='flujo',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
