# Generated by Django 2.0.7 on 2018-11-05 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0003_auto_20181104_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciahistoria',
            name='instanciaflujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='flujo.InstanciaFlujo'),
        ),
        migrations.AlterField(
            model_name='instanciahistoriadetalle',
            name='instanciahistoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_detalle', to='flujo.InstanciaHistoria'),
        ),
    ]
