# Generated by Django 2.0.7 on 2018-11-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0004_auto_20181104_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instanciahistoria',
            options={'ordering': ['instanciaflujo', 'created_at', 'accion', 'idinstanciahistoria']},
        ),
    ]
