# Generated by Django 2.0.7 on 2018-11-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0005_auto_20181105_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
