# Generated by Django 2.0.7 on 2018-11-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0006_estado_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flujo',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
    ]
